### ISSUE TITLE
Normalization XL

### ISSUE THREAD

**Issue by tastez** [Haoming02/comfyui-diffusion-cg#3]
Hi - do we need to use this with the updated Hook Recenter XL node? It seems to funk up the output a bit. Im running the turbo xl / custom sampler combo (sorry) with the toggle on on the Recenter XL node. It seems like its not needed?

**Comment by Haoming02** [comment]
You can check out the [Extension](https://github.com/Haoming02/sd-webui-diffusion-cg) page for more info.
**Recenter** and **Normalizaion** are different effects.

Though, can you send a workflow with a few examples on the messed up outputs?

**Comment by tastez** [comment]
here you go. This is the SDXL Turbo workflow to generate 1 step 1 cfg images and the Hook recenter works really well (although i wish we could change the strength to an input and go beyond -/+1.0 range cap, maybe thats a simple edit on user side in the code though)
![ComfyUI_0007](https://github.com/Haoming02/comfyui-diffusion-cg/assets/78642112/fa3429f8-0393-4916-8762-8da26083165a)

 
![ComfyUI_0008](https://github.com/Haoming02/comfyui-diffusion-cg/assets/78642112/c8482faa-86d1-4da5-91e6-d5a63c984934)

**Comment by Haoming02** [comment]
Reduced the values a little bit so that it ~~hopefully~~ will not generate messed up colors again. ~~Though, this also means the effect is barely noticable now.~~

As for the strength, I still want to keep it at `0 ~ 1`, to have a easier scale to work with. Plus, values under 0 or over 1 tends to create even weirder colors.

If you really want them though, you can just edit the scirpt and change the `min` and `max` values.
